apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: script
spec:
  entrypoint: run
  templates:
    - name: run
      script:
        image: python:alpine3.6
        command: [python]
        source: |
          import random
          i = random.randint(1, 100)
          print(i)
